name: hexa-policy-opa

services:
  bundle-server:
    image: independentid/hexaopa:latest
    container_name: hexa-bundle-server
    ports:
      - "8889:8889"
    command: /app/testBundleServer
    environment:
      PORT: 8889
      HEXA_CERT_DIRECTORY: "/home/certs"
      SERVER_CERT: "/home/certs/server-cert.pem"
      SERVER_KEY: "/home/certs/server-key.pem"
      BUNDLE_DIR: "/home/resources/bundles"
    volumes:
      - "./bundleServer:/home/resources"
      - "./.certs:/home/certs"

  hexa-opa-agent:
    image: independentid/hexaopa:latest
    container_name: hexa-opa-server
    ports:
      - "8887:8887"
    depends_on:
      - bundle-server
    command: /app/hexaOpa run --server --addr :8887 --log-level debug -c /home/config/config.yaml
    environment:
      # These environment values are referenced in ./deployments/hexaOpaServer/config/config.yaml
      HEXA_CERT_DIRECTORY: "/home/certs"
      HEXA_CONFIG_URL: "https://hexa-bundle-server:8889"
      HEXA_CA_CERT: "/home/certs/ca-cert.pem"
    volumes:
      - "./config:/home/config:ro"
      - "./.opa:/app/.opa"
      - "./.certs:/home/certs:ro"
