name: 'CodeQL Config File'

paths:
  - cmd/mapTool
  - pkg/hexapolicy
  - pkg/hexapolicysupport
  - mapper/conditionLangs/gcpcel
  - mapper/formats/awsCedar
  - mapper/formats/gcpBind
  - providers/aws/avp