name: 'CodeQL Config File'

paths:
  - cmd/mapTool
  - pkg/hexapolicy
  - pkg/hexapolicysupport
  - models/conditionLangs/gcpcel
  - models/formats/awsCedar
  - models/formats/gcpBind
  - models/rbac
  - models/testhelper
  - providers/aws
  - providers/googlecloud
  - providers/openpolicyagent
  - sdk