name: build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.19'
          check-latest: true
          cache-dependency-path: |
            ./cmd/mapTool/go.sum
           	./hexaIdql/go.sum
           	./mapper/conditionLangs/gcpcel/go.sum
           	./mapper/formats/awsCedar/go.sum
           	./mapper/formats/gcpBind /go.sum
      - name: test
        run: |
          sh ./build.sh -t
